FROM node:16-alpine
 
USER node
 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
 
COPY --chown=node:node ./package.json ./
RUN npm install
RUN npm install react-bootstrap bootstrap
COPY --chown=node:node ./ ./
 
CMD ["npm", "start"]